---
# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 The Linux Foundation

# Runs on a new pull request, performs build and runs tests
name: 'Python Build/Test'

# yamllint disable-line rule:truthy
on:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - main

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

permissions: {}

jobs:
  build-test:
    permissions:
      contents: read
      pull-requests: read
    # yamllint disable-line rule:line-length
    uses: lfreleng-actions/python-workflows/.github/workflows/build-test.yaml@b29621b4859bf5b6fbd7202977cd73334f54e29d  # v0.4.0
    with:
      audit_ignore_vulns: 'GHSA-58qw-9mgm-455v'
      audit_permit_fail: ${{ vars.NO_BLOCK_AUDIT_FAIL == 'true' }}
