---
# SPDX-FileCopyrightText: 2026 Andrew Grimberg <tykeal@bardicgrove.org>
# SPDX-License-Identifier: Apache-2.0

name: 'Release Drafter'

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - main

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  update_release_draft:
    name: 'Update Release Draft'
    permissions:
      contents: write
      pull-requests: read
    runs-on: 'ubuntu-latest'
    timeout-minutes: 3
    steps:
      # yamllint disable-line rule:line-length
      - uses: lfreleng-actions/harden-runner-block-action@6db537b3e6d060c3287c5a3ce2c28b55b0af330d  # v0.2.1
        with:
          # yamllint disable-line rule:line-length
          config: 'lfreleng-actions//.github/harden-runner/lfreleng-actions/allow_list.txt@18d9c4446bea555d0783e850f6d295f844fe8f67'  # v0.1.1
      - name: 'Harden runner (block)'
        # yamllint disable-line rule:line-length
        uses: step-security/harden-runner@e14015d583714f6e62063499dc959a02595150a1  # v2.21.1
        with:
          egress-policy: 'block'
          allowed-endpoints: >
            ${{ env.CONNECTION_ALLOW_LIST }}

      # yamllint disable-line rule:line-length
      - uses: release-drafter/release-drafter@4d75298e00d9e34c483e5ff8c68d0ea1c1940c1e # v7.5.1
